<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "functionaltest_test"
 *
 * Auto generated by Extension Builder 2016-12-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Functionaltest Test extension',
	'description' => 'With this extension you can test if the functional tests for extensions work properly.',
	'category' => 'plugin',
	'author' => 'Uwe Trotzek',
	'author_email' => 'uwe.trotzek@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);